### ISSUE TITLE
thumbnailFormat=maxres

### ISSUE THREAD

**Issue by distantnative** [felixgirault/essence#85]
Would be great to add also the option "maxres" for thumbnailFormat:

$oEmbed = $Essence->embed($text, [
      'thumbnailFormat' => 'maxres'
  ]);

and

case 'maxres':
	$url = str_replace( 'hqdefault', 'maxresdefault', $url );
	break;

**Comment by distantnative** [comment]
Also noticed that thumbnailWidth and thumbnailHeight are not changed when setting thumbnailFormat :/

**Comment by felixgirault** [comment]
Thanks for the suggestion, I'll work on it.
About thumbnail dimensions, updating them would probably require another request to the provider so I'll see what could be done.

**Comment by felixgirault** [comment]
I updated the current and the upcoming 3.0 version to handle the "maxres" format.
See https://github.com/felixgirault/essence/pull/86 and https://github.com/felixgirault/essence/pull/87.

I also created another issue about thumbnails dimensions: https://github.com/felixgirault/essence/issues/88.

Hope that it will fit your needs ;)
