### ISSUE TITLE
Install essence on laravel

### ISSUE THREAD

**Issue by lmhaydi** [felixgirault/essence#89]
Please, how i can install and use essence package on laravel ?

**Comment by felixgirault** [comment]
Hi,

I'm sorry, I don't know anything about Laravel...
However, I don't think you need anything special, you could probably install essence through composer, and use it like any other library.

If it is of any help, you can see an example of a CakePHP integration here : https://github.com/felixgirault/cakephp-essence

**Comment by lmhaydi** [comment]
Thanks for your response.
